In [1]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

warnings.filterwarnings("ignore")         
pd.set_option("display.max_columns", 30) 
pd.set_option("display.width", 120)

print("NumPy  :", np.__version__)
print("Pandas :", pd.__version__)
print("sklearn:", sklearn.__version__)

NumPy  : 2.5.2
Pandas : 3.0.6
sklearn: 1.9.1

In [2]:
s = pd.Series([120, 95, 140], index=["Mon", "Tue", "Wed"], name="rooms_sold")
print(s, "\n")
print("s[' Tue'] =", s["Tue"],"| s.mean() =", s.mean())

Mon    120
Tue     95
Wed    140
Name: rooms_sold, dtype: int64

s[' Tue'] = 95 | s.mean() = 118.33333333333333

In [3]:
orders = pd.DataFrame({
    "order_id":    range(1001, 1013),
    "customer_id": [1, 2, 3, 1, 4, 2, 5, 3, 6, 1, 7, 4],
    "city":        ["Delhi", "Mumbai", "Ludhiana", "Delhi", "Pune", "Mumbai",
                    "Delhi", "Ludhiana", "Chandigarh", "Delhi", "Pune", "Pune"],
    "product":     ["Laptop", "Phone", "Tablet", "Phone", "Laptop", "Headphones",
                    "Phone", "Laptop", "Tablet", "Headphones", "Phone", "Laptop"],
    "qty":         [1, 2, 1, 1, 1, 3, 2, 1, 2, 2, 1, 1],
    "unit_price":  [55000, 20000, 25000, 20000, 55000, 3000, 20000, 55000, 25000, 3000, 20000, 55000],
    "order_date":  pd.to_datetime(["2025-01-05", "2025-01-12", "2025-02-03", "2025-02-14",
                                   "2025-02-20", "2025-03-01", "2025-03-09", "2025-03-15",
                                   "2025-04-02", "2025-04-18", "2025-05-05", "2025-05-21"]),
    "status":      ["Delivered", "Delivered", "Cancelled", "Delivered", "Delivered", "Delivered",
                    "Returned", "Delivered", "Delivered", "Cancelled", "Delivered", "Delivered"],
})
orders

    order_id  customer_id        city     product  qty  unit_price order_date     status
0       1001            1       Delhi      Laptop    1       55000 2025-01-05  Delivered
1       1002            2      Mumbai       Phone    2       20000 2025-01-12  Delivered
2       1003            3    Ludhiana      Tablet    1       25000 2025-02-03  Cancelled
3       1004            1       Delhi       Phone    1       20000 2025-02-14  Delivered
4       1005            4        Pune      Laptop    1       55000 2025-02-20  Delivered
5       1006            2      Mumbai  Headphones    3        3000 2025-03-01  Delivered
6       1007            5       Delhi       Phone    2       20000 2025-03-09   Returned
7       1008            3    Ludhiana      Laptop    1       55000 2025-03-15  Delivered
8       1009            6  Chandigarh      Tablet    2       25000 2025-04-02  Delivered
9       1010            1       Delhi  Headphones    2        3000 2025-04-18  Cancelled
10      1011            7        Pune       Phone    1       20000 2025-05-05  Delivered
11      1012            4        Pune      Laptop    1       55000 2025-05-21  Delivered

In [4]:
print("Shape:", orders.shape)
print()
orders.info()

Shape: (12, 8)

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     12 non-null     int64
 1   customer_id  12 non-null     int64
 2   city         12 non-null     str
 3   product      12 non-null     str
 4   qty          12 non-null     int64
 5   unit_price   12 non-null     int64
 6   order_date   12 non-null     datetime64[us]
 7   status       12 non-null     str
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 900.0 bytes

In [5]:
print(orders.describe())
print()
print(orders["status"].value_counts())
print()
print("Unique cities:", orders["city"].nunique(), "->", orders["city"].unique())

          order_id  customer_id      qty    unit_price           order_date
count    12.000000    12.000000  12.0000     12.000000                   12
mean   1006.500000     3.250000   1.5000  29666.666667  2025-03-08 22:00:00
min    1001.000000     1.000000   1.0000   3000.000000  2025-01-05 00:00:00
25%    1003.750000     1.750000   1.0000  20000.000000  2025-02-11 06:00:00
50%    1006.500000     3.000000   1.0000  22500.000000  2025-03-05 00:00:00
75%    1009.250000     4.250000   2.0000  55000.000000  2025-04-06 00:00:00
max    1012.000000     7.000000   3.0000  55000.000000  2025-05-21 00:00:00
std       3.605551     2.005674   0.6742  20015.145780                  NaN

status
Delivered    9
Cancelled    2
Returned     1
Name: count, dtype: int64

Unique cities: 5 -> <StringArray>
['Delhi', 'Mumbai', 'Ludhiana', 'Pune', 'Chandigarh']
Length: 5, dtype: str

In [6]:
print(orders["city"].head(3).tolist())
print()
print(orders[["order_id", "city", "qty"]].head(3))
print()
print("loc  (label-based)   :", orders.loc[0:2, "product"].tolist(), " <- loc INCLUDES the end label")
print("iloc (position-based):", orders.iloc[0:2, 3].tolist(), " <- iloc EXCLUDES the end position")

['Delhi', 'Mumbai', 'Ludhiana']

   order_id      city  qty
0      1001     Delhi    1
1      1002    Mumbai    2
2      1003  Ludhiana    1

loc  (label-based)   : ['Laptop', 'Phone', 'Tablet']  <- loc INCLUDES the end label
iloc (position-based): ['Laptop', 'Phone']  <- iloc EXCLUDES the end position

In [8]:
# Single condition
delivered = orders[orders["status"] == "Delivered"]
print("Delivered orders:", len(delivered))

# Multiple conditions: use & | ~ and put EACH condition in parentheses
big_delhi = orders[(orders["city"] == "Delhi") & (orders["unit_price"] > 10000)]
print("Delhi orders above 10,000:", len(big_delhi))

# isin, between, string contains
print("\nPune or Mumbai:", orders[orders["city"].isin(["Pune", "Mumbai"])]["order_id"].tolist())
print("Price between 20k and 30k:", orders[orders["unit_price"].between(20000, 30000)]["order_id"].tolist())
print("Product contains 'phone':", orders[orders["product"].str.contains("phone", case=False)]["product"].unique())

# query(): readable alternative
print("\nUsing query():")
orders.query("qty >= 2 and status == 'Delivered'")[["order_id", "product", "qty", "status"]]

Delivered orders: 9
Delhi orders above 10,000: 3

Pune or Mumbai: [1002, 1005, 1006, 1011, 1012]
Price between 20k and 30k: [1002, 1003, 1004, 1007, 1009, 1011]
Product contains 'phone': <StringArray>
['Phone', 'Headphones']
Length: 2, dtype: str

Using query():

   order_id     product  qty     status
1      1002       Phone    2  Delivered
5      1006  Headphones    3  Delivered
8      1009      Tablet    2  Delivered

In [12]:
df = orders.copy()                                 # work on a copy so `orders` stays original

df["revenue"] = df["qty"] * df["unit_price"]       # new column from math
df["is_bulk"] = df["qty"] >= 2                     # True/False column
df["price_band"] = np.where(df["unit_price"] > 30000, "Premium", "Standard")   # if-else
df["city_upper"] = df["city"].str.upper()          # string method
df["month"] = df["order_date"].dt.month            # date part

# map(): replace values using a dictionary
df["status_code"] = df["status"].map({"Delivered": 1, "Returned": 0, "Cancelled": 0})

# apply(): run any Python function per value (slower than vectorised, use when needed)
df["label"] = df["revenue"].apply(lambda r: "High" if r >= 50000 else "Normal")

df[["order_id", "revenue", "is_bulk", "price_band", "month", "status_code", "label", "qty", "unit_price", "city_upper"]].head()

   order_id  revenue  is_bulk price_band  month  status_code   label  qty  unit_price city_upper
0      1001    55000    False    Premium      1            1    High    1       55000      DELHI
1      1002    40000     True   Standard      1            1  Normal    2       20000     MUMBAI
2      1003    25000    False   Standard      2            0  Normal    1       25000   LUDHIANA
3      1004    20000    False   Standard      2            1  Normal    1       20000      DELHI
4      1005    55000    False    Premium      2            1    High    1       55000       PUNE

In [16]:
print(df.sort_values("revenue", ascending=False)[["order_id", "city", "revenue"]].head(10))
print()
print("nlargest shortcut:")
print(df.nlargest(5, "revenue")[["order_id", "product", "revenue"]])

    order_id        city  revenue
0       1001       Delhi    55000
11      1012        Pune    55000
7       1008    Ludhiana    55000
4       1005        Pune    55000
8       1009  Chandigarh    50000
6       1007       Delhi    40000
1       1002      Mumbai    40000
2       1003    Ludhiana    25000
3       1004       Delhi    20000
10      1011        Pune    20000

nlargest shortcut:
    order_id product  revenue
0       1001  Laptop    55000
4       1005  Laptop    55000
7       1008  Laptop    55000
11      1012  Laptop    55000
8       1009  Tablet    50000

In [17]:
valid = df[df["status"] == "Delivered"]       # only count delivered orders as real revenue

# One key, one metric
print(valid.groupby("city")["revenue"].sum().sort_values(ascending=False))

city
Pune          130000
Delhi          75000
Ludhiana       55000
Chandigarh     50000
Mumbai         49000
Name: revenue, dtype: int64

In [18]:
summary = valid.groupby("city").agg(
    orders=("order_id", "count"),
    total_revenue=("revenue", "sum"),
    avg_order_value=("revenue", "mean"),
    unique_customers=("customer_id", "nunique"),
).sort_values("total_revenue", ascending=False)
summary

            orders  total_revenue  avg_order_value  unique_customers
city
Pune             3         130000     43333.333333                 2
Delhi            2          75000     37500.000000                 1
Ludhiana         1          55000     55000.000000                 1
Chandigarh       1          50000     50000.000000                 1
Mumbai           2          49000     24500.000000                 1

In [19]:
print(valid.groupby(["city", "product"])["revenue"].sum().head(6))
print()
pivot = valid.pivot_table(index="city", columns="product", values="revenue", aggfunc="sum", fill_value=0)
pivot

city        product
Chandigarh  Tablet        50000
Delhi       Laptop        55000
            Phone         20000
Ludhiana    Laptop        55000
Mumbai      Headphones     9000
            Phone         40000
Name: revenue, dtype: int64

product     Headphones  Laptop  Phone  Tablet
city
Chandigarh           0       0      0   50000
Delhi                0   55000  20000       0
Ludhiana             0   55000      0       0
Mumbai            9000       0  40000       0
Pune                 0  110000  20000       0

In [20]:
df["city_total_revenue"] = df.groupby("city")["revenue"].transform("sum")
df["share_of_city_revenue"] = (df["revenue"] / df["city_total_revenue"]).round(2)
df[["order_id", "city", "revenue", "city_total_revenue", "share_of_city_revenue"]].head(5)

   order_id      city  revenue  city_total_revenue  share_of_city_revenue
0      1001     Delhi    55000              121000                   0.45
1      1002    Mumbai    40000               49000                   0.82
2      1003  Ludhiana    25000               80000                   0.31
3      1004     Delhi    20000              121000                   0.17
4      1005      Pune    55000              130000                   0.42

In [24]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6, 7],          
    "name":        ["Aman", "Priya", "Rahul", "Simran", "Karan", "Neha", "John"],
    "segment":     ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold", "Gold"],
})

inner = orders.merge(customers, on="customer_id", how="inner")
left  = orders.merge(customers, on="customer_id", how="left")

print("orders rows :", len(orders))
print("inner join  :", len(inner), "rows  <- customer 7's order disappeared silently!")
print("left join   :", len(left), "rows  <- nothing lost, missing info shows as NaN")
print()
print(left[["order_id", "customer_id", "name", "segment"]])

orders rows : 12
inner join  : 12 rows  <- customer 7's order disappeared silently!
left join   : 12 rows  <- nothing lost, missing info shows as NaN

    order_id  customer_id    name segment
0       1001            1    Aman    Gold
1       1002            2   Priya  Silver
2       1003            3   Rahul    Gold
3       1004            1    Aman    Gold
4       1005            4  Simran  Bronze
5       1006            2   Priya  Silver
6       1007            5   Karan  Silver
7       1008            3   Rahul    Gold
8       1009            6    Neha    Gold
9       1010            1    Aman    Gold
10      1011            7    John    Gold
11      1012            4  Simran  Bronze

In [26]:
d = pd.DataFrame({"raw": ["2025-01-05", "2025-02-14", "not available", "2025-03-09"]})
print(d)
d["date"] = pd.to_datetime(d["raw"], errors="coerce")      
d["year"]       = d["date"].dt.year
d["month_name"] = d["date"].dt.month_name()
d["weekday"]    = d["date"].dt.day_name()
d["is_weekend"] = d["date"].dt.dayofweek >= 5               
print(d)

# Monthly revenue trend
monthly = df.groupby(df["order_date"].dt.to_period("M"))["revenue"].sum()
print("\nMonthly revenue:\n", monthly)

             raw
0     2025-01-05
1     2025-02-14
2  not available
3     2025-03-09
             raw       date    year month_name weekday  is_weekend
0     2025-01-05 2025-01-05  2025.0    January  Sunday        True
1     2025-02-14 2025-02-14  2025.0   February  Friday       False
2  not available        NaT     NaN        NaN     NaN       False
3     2025-03-09 2025-03-09  2025.0      March  Sunday        True

Monthly revenue:
 order_date
2025-01     95000
2025-02    100000
2025-03    104000
2025-04     56000
2025-05     75000
Freq: M, Name: revenue, dtype: int64

In [27]:
messy = pd.Series(["Delhi", " delhi ", "DELHI", "New Delhi", "Dehli"])
print("Before:", messy.value_counts().to_dict())

clean_city = (messy.str.strip()          
                    .str.title()         
                    .replace({"New Delhi": "Delhi", "Dehli": "Delhi"}))    
print("After :", clean_city.value_counts().to_dict())

Before: {'Delhi': 1, ' delhi ': 1, 'DELHI': 1, 'New Delhi': 1, 'Dehli': 1}
After : {'Delhi': 5}